# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "lesson10"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provider "libvirt" do |lb|
      lb.memory = "1024"
      lb.cpus = "2"
    end
     config.vm.provision "shell" do |s|
        s.path = "script.sh"
        s.privileged = false
     end
#    config.vm.provision "file", source: "./login.sh", destination: "/usr/local/bin/"
end
