version: '3.7'
services:
  mysql-server1:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.15
    ports:
      - "3301:3306"
    command: ["mysqld",
        "--server_id=1",
        "--binlog_checksum=NONE",
        "--gtid_mode=ON",
        "--enforce_gtid_consistency=ON",
        "--log_bin","--log_slave_updates=ON",
        "--master_info_repository=TABLE",
        "--relay_log_info_repository=TABLE",
        "--transaction_write_set_extraction=XXHASH64",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve", 
        "--default_authentication_plugin=mysql_native_password"]
  mysql-server2:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.15
    command: ["mysqld",
        "--server_id=2",
        "--binlog_checksum=NONE",
        "--gtid_mode=ON",
        "--enforce_gtid_consistency=ON",
        "--log_bin",
        "--log_slave_updates=ON",
        "--master_info_repository=TABLE",
        "--relay_log_info_repository=TABLE",
        "--transaction_write_set_extraction=XXHASH64",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve", 
        "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
  mysql-server3:
    env_file:
      - mysql-server.env
    image: mysql/mysql-server:8.0.15
    command: ["mysqld",
        "--server_id=3",
        "--binlog_checksum=NONE",
        "--gtid_mode=ON",
        "--enforce_gtid_consistency=ON",
        "--log_bin",
        "--log_slave_updates=ON",
        "--master_info_repository=TABLE",
        "--relay_log_info_repository=TABLE",
        "--transaction_write_set_extraction=XXHASH64",
        "--user=mysql",
        "--skip-host-cache",
        "--skip-name-resolve", 
        "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
  mysql-shell:
    env_file:
      - mysql-shell.env
    image: mysql/mysql-server:8.0.15
    entrypoint: "/bin/bash"
    command: ["-c", "/scripts/entrypoint.sh"]
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - mysql-server1
      - mysql-server2
      - mysql-server3
  mysql-router:
    env_file:
      - mysql-router.env
    image: mysql/mysql-router
    ports:
      - "6446:6446"
    depends_on:
      - mysql-server1
      - mysql-server2
      - mysql-server3
      - mysql-shell
    restart: on-failure
