version: "3"

services:
  web:
    image: otusnginx:0.1
    container_name: web
    ports:
      - 8080:80
    volumes:
      - ./phpinfo.php:/usr/share/nginx/html/info.php
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
         - php
    networks:
      - www

  php:
    image: otusphpfpm:0.1
    container_name: php
    volumes:
      - ./phpinfo.php:/usr/share/nginx/html/info.php
    networks:
      - www

networks:
  www:
    driver: bridge
