# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define :server do |srv|
    srv.vm.hostname = "server"
    srv.vm.network "private_network", ip: "192.168.33.10"
    srv.vm.provider "libvirt" do |lb|
        lb.memory = "1024"
        lb.cpus = "2"
    end
  end

  config.vm.define :client do |cln|
    cln.vm.hostname = "client"
    cln.vm.network "private_network", ip: "192.168.33.11"
    cln.vm.provider "libvirt" do |lb|
        lb.memory = "1024"
        lb.cpus = "2"
    end
  end
end

