# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "lesson9"
    config.vm.network "forwarded_port", guest: 8080, host: 8080
    config.vm.network "private_network", ip: "192.168.33.10"
    config.vm.provider "libvirt" do |lb|
      lb.memory = "1024"
      lb.cpus = "2"
    end
     config.vm.provision :ansible do |ansible|
        ansible.playbook = "ansible/nginx.yml"
     end
end
