# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define :master do |srv|
    srv.vm.hostname = "master"
    srv.vm.network "private_network", ip: "192.168.11.150"
    srv.vm.provider "libvirt" do |lb|
        lb.memory = "2048"
        lb.cpus = "2"
    end
  end

  config.vm.define :slave do |cln|
    cln.vm.hostname = "slave"
    cln.vm.network "private_network", ip: "192.168.11.151"
    cln.vm.provider "libvirt" do |lb|
        lb.memory = "1024"
        lb.cpus = "2"
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = "true"
    ansible.extra_vars = {new_db_pass: "",
                          repl_pass: ""}
  end
end
