# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

    config.vm.provider "libvirt" do |lb|
      lb.memory = "512"
    end

  config.vm.define "server" do |srv|
    srv.vm.network "private_network", ip: "192.168.10.10"
    srv.vm.hostname = "server"
  end

  config.vm.define "client" do |cln|
    cln.vm.network "private_network", ip: "192.168.10.20"
    cln.vm.hostname = "client"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.sudo = "true"
    ansible.extra_vars = {openvpn_dev: "tap",
                          openvpn_rasvpn: false}
  end


end

